### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by danisuba10** [GatoLoko/novel2epub#2]
(ve) C:\Users\Dan\Desktop\ve\novel2epub-master>python novel2epub.py ed 37
Loaded ed module
Volume start: 3601
Volume end: 3700
Title: Emperor's domination - Vol37
Chapters: 100
Filename: Emperor's domination - Vol37.epub
Processing: https://www.wuxiaworld.com/novel/emperors-domination/emperor-chapter-3601
Traceback (most recent call last):
  File "C:\Users\Dan\Desktop\ve\novel2epub-master\novel2epub.py", line 96, in <module>
    ch_title, ch_file, ch_text = common.get_chapter(i)
  File "C:\Users\Dan\Desktop\ve\novel2epub-master\libs\common.py", line 138, in get_chapter
    chapter_title, contents = get_wuxiaworld_com(html)
  File "C:\Users\Dan\Desktop\ve\novel2epub-master\libs\common.py", line 56, in get_wuxiaworld_com
    contents = html.find('div', 'panel-default').find('div', 'fr-view')
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by GatoLoko** [comment]
I'm already aware of this problem.

Several novels, including "Emperor's domination", were obtained from wuxiaworld.com, but they changed their web recently to a new one that's populated through javascript. This forces us to either implement javascript support in novel2epub or find new sources for the same content.

I've been testing other sources and will fix this soon.
